- name: nginxのデータボリューム用ディレクトリが存在すること
  file:
    path: /data/nginx/conf.d
    state: directory
    recurse: yes
    owner: root
    group: root
    mode: 0755

- name: nginxの設定ファイルが存在すること
  template:
    src: ../templates/data/nginx/nginx.conf.j2
    dest: /data/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  # notify: reload_nginx

- name: nginxのサービス別設定ファイルが存在すること
  template:
    src: "../templates/data/nginx/conf.d/{{ item }}.j2"
    dest: "/data/nginx/conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
  - "default.conf"
  - "prometheus.conf.ctmpl"
  # notify: reload_nginx

- name: デフォルト用ドキュメントルートが存在すること
  file:
    path: /data/nginx/public
    state: directory
    owner: root
    group: root
    mode: 0755

- name: デフォルト用ドキュメントルートのファイルが存在すること
  template:
    src: "../templates/data/nginx/public/{{ item }}.j2"
    dest: "/data/nginx/public/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
  - "index.html"
