- name: reload_consul
  service:
    name: consul-server
    state: reloaded

- name: reload_nomad_server
  service:
    name: nomad-server
    state: reloaded

- name: reload_nomad_client
  service:
    name: nomad-client
    state: reloaded

- name: reload_vault_server
  service:
    name: vault-server
    state: reloaded

- name: reload_nginx
  service:
    name: nginx
    state: reloaded

- name: reload_systemd
  systemd:
    daemon_reload: yes
