- name: reload_consul
  service:
    name: consul-server
    state: reloaded

- name: reload_nomad_server
  service:
    name: nomad-server
    state: reloaded

- name: reload_nomad_client
  service:
    name: nomad-client
    state: reloaded

- name: restart_dnsmasq
  service:
    name: dnsmasq
    state: restarted

- name: reload_systemd
  systemd:
    daemon_reload: yes
