- name: consul-templateがインストールされていること
  stat: path=/usr/local/bin/consul-template
  register: consul_template_stat_result

- name: consul-templateのダウンロード
  get_url:
    url: https://releases.hashicorp.com/consul-template/0.20.0/consul-template_0.20.0_linux_amd64.tgz
    dest: /tmp/consul-template_0.20.0_linux_amd64.tgz
  when: not consul_template_stat_result.stat.exists

- name: consul-templateのインストール
  unarchive:
    src: /tmp/consul-template_0.20.0_linux_amd64.tgz
    dest: /usr/local/bin
    mode: 0755
    owner: root
    group: root
    remote_src: yes
  when: not consul_template_stat_result.stat.exists

- name: consul-templateのtarballが存在しないこと
  file:
    path: /tmp/consul-template_0.20.0_linux_amd64.tgz
    state: absent
