- name: consulがインストールされていること
  stat: path=/usr/local/bin/consul
  register: consul_stat_result

- name: consulのダウンロード
  get_url:
    url: https://releases.hashicorp.com/consul/1.4.4/consul_1.4.4_linux_amd64.zip
    dest: /tmp/consul_1.4.4_linux_amd64.zip
  when: not consul_stat_result.stat.exists

- name: consulのインストール
  unarchive:
    src: /tmp/consul_1.4.4_linux_amd64.zip
    dest: /usr/local/bin
    mode: 0755
    owner: root
    group: root
    remote_src: yes
  when: not consul_stat_result.stat.exists

- name: consulのzipが存在しないこと
  file:
    path: /tmp/consul_1.4.4_linux_amd64.zip
    state: absent

- name: consulの設定ファイルディレクトリが存在すること
  file:
    path: /etc/consul
    state: directory
    owner: root
    group: root
    mode: 0755

- name: consulのデータディレクトリが存在すること
  file:
    path: /var/lib/consul
    state: directory
    owner: root
    group: root
    mode: 0755

- name: consulの設定ファイルが存在すること
  template:
    src: ../templates/etc/consul/consul-server.json.j2
    dest: /etc/consul/consul-server.json
    owner: root
    group: root
    mode: 0644
  notify: reload_consul

- name: consulのsystemd設定が存在すること
  template:
    src: ../templates/etc/systemd/system/consul-server.service.j2
    dest: /etc/systemd/system/consul-server.service
    owner: root
    group: root
    mode: 0644
  notify: reload_systemd

- name: consulが自動起動する設定になっていること
  systemd:
    name: consul-server.service
    enabled: true
    state: started
