- hosts: all
  become: true
  vars_files:
  - "group_vars/vagrant.yml"
  - "group_vars/vagrant-s1.yml"
  roles:
  - role: common
    tags: common
  - role: nomad
    tags: nomad
  - role: application
    tags: application
